if game.PlaceId == 16732694052 then
	loadstring(game:HttpGet("https://raw.githubusercontent.com/eSKa-0/jasper-hub/refs/heads/main/jhubfisch.luau"))()
elseif game.PlaceId == 142823291 then
	loadstring(game:HttpGet("https://raw.githubusercontent.com/eSKa-0/jasper-hub/refs/heads/main/jhubmm2.luau"))()
elseif game.PlaceId == 79546208627805 then
	loadstring(game:HttpGet("https://raw.githubusercontent.com/eSKa-0/jasper-hub/refs/heads/main/jhub99nitf.luau"))()
else
	game.Players.LocalPlayer:Kick("Game Not Supported")
end
